name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2.7.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 5a7485ff-fbc6-466d-b274-2864627af885
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
